server:
  port: 8006
  servlet:
    context-path: /

spring:
  application:
    name: cloud-payment-service
  cloud:
    consul:
      host: localhost
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
      port: 8500

