server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.219.110:3306/cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: liuwei
    password: liuwei
    druid:
      filters: stat
      initial-size: 2
      max-active: 300
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 200

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.toolv.springcloud.entities
