server:
  port: 8002

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.219.110:3306/cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: liuwei
    password: liuwei
    druid:
      filters: stat
      initial-size: 2
      max-active: 300
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 200

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.toolv.springcloud.entities

eureka:
  client:
    # 是否从EurekaServer抓取已有的注册信息, 默认为true. 单节点无所谓, 进群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    # 表示是否将自己注册进EurekaServer 默认-true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka,http://eureka7003:7003/eureka
  instance:
    # 在页面中的显示名称优化, 可以启动后与 cloud-provider-payment8001 做一下对比
    instance-id: payment8002
    prefer-ip-address: true
    # 客户端想服务端发送心跳的时间间隔, 单位为秒(默认30)
    lease-renewal-interval-in-seconds: 1
    # 服务端手段哦最后一次心跳后等待时间上限, 单位为秒(默认90), 超时将移除服务
    lease-expiration-duration-in-seconds: 2
